"""
Pydantic Models for CMDB - vpn/ipsec/concentrator

Runtime validation models for vpn/ipsec/concentrator configuration.
Generated from FortiOS schema version unknown.

Example Usage:
    >>> from hfortix_fortios.models.cmdb.vpn.ipsec.concentrator import 
    >>>
    >>> # Create with validation
    >>> obj = (
    ...     id=1,
    ...     name="example",
    ... )
    >>>
    >>> # Validation happens automatically
    >>> # ValidationError raised if constraints violated
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator
from typing import Any, Literal, Optional

# ============================================================================
# Child Table Models
# ============================================================================

class ConcentratorMember(BaseModel):
    """
    Child table model for member.
    
    Names of up to 3 VPN tunnels to add to the concentrator.
    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
    
    name: str = Field(max_length=79, default="", description="Member name.")  # datasource: ['vpn.ipsec.manualkey.name', 'vpn.ipsec.phase1.name']
# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================


# ============================================================================
# Main Model
# ============================================================================

class ConcentratorModel(BaseModel):
    """
    Pydantic model for vpn/ipsec/concentrator configuration.
    
    Concentrator configuration.
    
    Validation Rules:        - id: min=1 max=65535 pattern=        - name: max_length=35 pattern=        - src_check: pattern=        - member: pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    id: int | None = Field(ge=1, le=65535, default=0, description="Concentrator ID (1 - 65535).")    
    name: str | None = Field(max_length=35, default="", description="Concentrator name.")    
    src_check: Literal["disable", "enable"] | None = Field(default="disable", description="Enable to check source address of phase 2 selector. Disable to check only the destination selector.")    
    member: list[Member] = Field(default=None, description="Names of up to 3 VPN tunnels to add to the concentrator.")    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)


# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "ConcentratorModel",    "ConcentratorMember",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-06T20:14:34.596592Z
# ============================================================================