"""
Pydantic Models for MONITOR - vpn/ipsec/tunnel_down

Runtime validation models for vpn/ipsec/tunnel_down configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "TunnelDownModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T21:00:58.256549Z
# ============================================================================