"""
Pydantic Models for MONITOR - vpn/ipsec/tunnel_reset_stats

Runtime validation models for vpn/ipsec/tunnel_reset_stats configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "TunnelResetStatsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-14T22:43:41.566660Z
# ============================================================================
