from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_MONITOR_ALL_MESSAGES: Literal["disable", "enable"]
VALID_BODY_LOG_PACKET: Literal["disable", "enable"]
VALID_BODY_TRACK_REQUESTS_ANSWERS: Literal["disable", "enable"]
VALID_BODY_MISSING_REQUEST_ACTION: Literal["allow", "block", "reset", "monitor"]
VALID_BODY_PROTOCOL_VERSION_INVALID: Literal["allow", "block", "reset", "monitor"]
VALID_BODY_MESSAGE_LENGTH_INVALID: Literal["allow", "block", "reset", "monitor"]
VALID_BODY_REQUEST_ERROR_FLAG_SET: Literal["allow", "block", "reset", "monitor"]
VALID_BODY_CMD_FLAGS_RESERVE_SET: Literal["allow", "block", "reset", "monitor"]
VALID_BODY_COMMAND_CODE_INVALID: Literal["allow", "block", "reset", "monitor"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...