"""
Pydantic Models for MONITOR - switch_controller/managed_switch/bios

Runtime validation models for switch_controller/managed_switch/bios configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "BiosModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-16T10:37:40.382240Z
# ============================================================================