"""
Pydantic Models for MONITOR - utm/blacklisted_certificates

Runtime validation models for utm/blacklisted_certificates configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "BlacklistedCertificatesModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-14T22:43:41.561597Z
# ============================================================================
