"""
Pydantic Models for MONITOR - router/bgp/clear_soft_in

Runtime validation models for router/bgp/clear_soft_in configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "ClearSoftInModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-05T01:53:54.297887Z
# ============================================================================