from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_MODEM_ID: Literal["modem1", "modem2", "all"]
VALID_BODY_TYPE: Literal["carrier", "slot", "iccid", "generic"]
VALID_BODY_SLOT: Literal["sim1", "sim2"]
VALID_BODY_AUTH_TYPE: Literal["none", "pap", "chap"]
VALID_BODY_PDN: Literal["ipv4-only", "ipv6-only", "ipv4-ipv6"]
VALID_BODY_OVERAGE: Literal["disable", "enable"]
VALID_BODY_PRIVATE_NETWORK: Literal["disable", "enable"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...