from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_AUTHORIZED: Literal["discovered", "disable", "enable"]
VALID_BODY_EXTENSION_TYPE: Literal["wan-extension", "lan-extension"]
VALID_BODY_OVERRIDE_ALLOWACCESS: Literal["enable", "disable"]
VALID_BODY_ALLOWACCESS: Literal["ping", "telnet", "http", "https", "ssh", "snmp"]
VALID_BODY_OVERRIDE_LOGIN_PASSWORD_CHANGE: Literal["enable", "disable"]
VALID_BODY_LOGIN_PASSWORD_CHANGE: Literal["yes", "default", "no"]
VALID_BODY_OVERRIDE_ENFORCE_BANDWIDTH: Literal["enable", "disable"]
VALID_BODY_ENFORCE_BANDWIDTH: Literal["enable", "disable"]
VALID_BODY_FIRMWARE_PROVISION_LATEST: Literal["disable", "once"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...