"""
Pydantic Models for MONITOR - system/config_sync/status

Runtime validation models for system/config_sync/status configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "StatusModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-16T13:33:08.314519Z
# ============================================================================