---
# Read the Docs configuration file for HFortix
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      # Install the package so autodoc can import it
      - pip install -e .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    # Install the main package with all dependencies
    - method: pip
      path: .
      extra_requirements:
        - dev
    # Install documentation dependencies
    - requirements: docs/requirements.txt

# Build PDF and ePub formats in addition to HTML
formats:
  - pdf
  - epub
