"""
Pydantic Models for MONITOR - registration/forticare/transfer

Runtime validation models for registration/forticare/transfer configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "TransferModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-16T10:37:39.819462Z
# ============================================================================