"""
Pydantic Models for MONITOR - switch_controller/detected_device

Runtime validation models for switch_controller/detected_device configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DetectedDeviceModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-21T16:05:14.239867Z
# ============================================================================