"""
Pydantic Models for MONITOR - system/upgrade_report/current

Runtime validation models for system/upgrade_report/current configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "CurrentModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-14T22:43:41.728929Z
# ============================================================================
