"""
Pydantic Models for CMDB - ethernet_oam/cfm

Runtime validation models for ethernet_oam/cfm configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "CfmModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.1
# Generated: 2026-01-18T15:06:45.551846Z
# ============================================================================