"""
Pydantic Models for MONITOR - system/external_resource/dynamic

Runtime validation models for system/external_resource/dynamic configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DynamicModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T22:00:19.588610Z
# ============================================================================