"""
Pydantic Models for MONITOR - log/forticloud_report_list

Runtime validation models for log/forticloud_report_list configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "ForticloudReportListModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-09T11:38:31.222443Z
# ============================================================================