"""
Pydantic Models for MONITOR - system/config_error_log/download

Runtime validation models for system/config_error_log/download configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DownloadModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-03T16:51:08.734857Z
# ============================================================================