"""
Pydantic Models for MONITOR - webfilter/malicious_urls

Runtime validation models for webfilter/malicious_urls configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "MaliciousUrlsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-16T13:33:07.325226Z
# ============================================================================