"""
Pydantic Models for MONITOR - system/ha_backup_hb_used

Runtime validation models for system/ha_backup_hb_used configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "HaBackupHbUsedModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-01T23:53:04.871945Z
# ============================================================================