"""
Pydantic Models for MONITOR - system/ha_checksums

Runtime validation models for system/ha_checksums configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "HaChecksumsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-21T16:05:13.848708Z
# ============================================================================