"""
Pydantic Models for MONITOR - system/vdom_resource

Runtime validation models for system/vdom_resource configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "VdomResourceModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-19T17:10:02.982487Z
# ============================================================================