"""
Pydantic Models for MONITOR - system/vm_information

Runtime validation models for system/vm_information configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "VmInformationModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-16T19:53:54.575831Z
# ============================================================================