"""
Pydantic Models for MONITOR - extension_controller/fortigate

Runtime validation models for extension_controller/fortigate configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "FortigateModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-03T21:12:47.244843Z
# ============================================================================