"""
Pydantic Models for MONITOR - user/device/query

Runtime validation models for user/device/query configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any, Optional

# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================


# ============================================================================
# Main Model
# ============================================================================

class QueryModel(BaseModel):
    """
    Pydantic model for user/device/query configuration.
    
    Retrieve user devices from user device store. List all the user devices if there is no filter set.
    
    Validation Rules:        - timestamp_from: pattern=        - timestamp_to: pattern=        - filters: pattern=        - query_type: pattern=        - view_type: pattern=        - query_id: pattern=        - cache_query: pattern=        - key_only: pattern=        - filter_logic: pattern=        - total_only: pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    timestamp_from: Any = Field(default=None)    
    timestamp_to: Any = Field(default=None)    
    filters: Any = Field(default=None)    
    query_type: str | None = Field(default=None)    
    view_type: str | None = Field(default=None)    
    query_id: Any = Field(default=None)    
    cache_query: Any = Field(default=None)    
    key_only: Any = Field(default=None)    
    filter_logic: str | None = Field(default=None)    
    total_only: Any = Field(default=None)    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "QueryModel":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)

# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "QueryModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-16T19:53:54.071254Z
# ============================================================================