"""
Pydantic Models for MONITOR - registration/forticloud/device_status

Runtime validation models for registration/forticloud/device_status configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DeviceStatusModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T15:11:46.238099Z
# ============================================================================