"""
Pydantic Models for MONITOR - registration/forticloud/domains

Runtime validation models for registration/forticloud/domains configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DomainsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-01T23:53:04.640000Z
# ============================================================================