"""
Pydantic Models for MONITOR - registration/vdom/add_license

Runtime validation models for registration/vdom/add_license configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "AddLicenseModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-09T11:38:30.673622Z
# ============================================================================