from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_LOG_BLOCKED_TRAFFIC: Literal["disable", "enable"]
VALID_BODY_AUTH_PORTAL: Literal["disable", "enable"]
VALID_BODY_DISPLAY_BOOKMARK: Literal["enable", "disable"]
VALID_BODY_FOCUS_BOOKMARK: Literal["enable", "disable"]
VALID_BODY_DISPLAY_STATUS: Literal["enable", "disable"]
VALID_BODY_DISPLAY_HISTORY: Literal["enable", "disable"]
VALID_BODY_POLICY_AUTH_SSO: Literal["enable", "disable"]
VALID_BODY_THEME: Literal["jade", "neutrino", "mariner", "graphite", "melongene", "jet-stream", "security-fabric", "dark-matter", "onyx", "eclipse"]
VALID_BODY_CLIPBOARD: Literal["enable", "disable"]
VALID_BODY_FORTICLIENT_DOWNLOAD: Literal["enable", "disable"]
VALID_BODY_CUSTOMIZE_FORTICLIENT_DOWNLOAD_URL: Literal["enable", "disable"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...