"""
Pydantic Models for CMDB - firewall/decrypted_traffic_mirror

Runtime validation models for firewall/decrypted_traffic_mirror configuration.
Generated from FortiOS schema version unknown.

Example Usage:
    >>> from hfortix_fortios.models.cmdb.firewall.decrypted_traffic_mirror import 
    >>>
    >>> # Create with validation
    >>> obj = (
    ...     name=1,
    ...     name="example",
    ... )
    >>>
    >>> # Validation happens automatically
    >>> # ValidationError raised if constraints violated
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator
from typing import Any, Literal, Optional

# ============================================================================
# Child Table Models
# ============================================================================

class DecryptedTrafficMirrorInterface(BaseModel):
    """
    Child table model for interface.
    
    Decrypted traffic mirror interface.
    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
    
    name: str | None = Field(max_length=79, default="", description="Decrypted traffic mirror interface.")  # datasource: ['system.interface.name']
# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================


# ============================================================================
# Main Model
# ============================================================================

class DecryptedTrafficMirrorModel(BaseModel):
    """
    Pydantic model for firewall/decrypted_traffic_mirror configuration.
    
    Configure decrypted traffic mirror.
    
    Validation Rules:        - name: max_length=35 pattern=        - dstmac: pattern=        - traffic_type: pattern=        - traffic_source: pattern=        - interface: pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    name: str = Field(max_length=35, default="", description="Name.")    
    dstmac: str | None = Field(default="ff:ff:ff:ff:ff:ff", description="Set destination MAC address for mirrored traffic.")    
    traffic_type: list[TrafficType] = Field(default="ssl", description="Types of decrypted traffic to be mirrored.")    
    traffic_source: Literal["client", "server", "both"] | None = Field(default="client", description="Source of decrypted traffic to be mirrored.")    
    interface: list[Interface] = Field(description="Decrypted traffic mirror interface.")    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)


# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DecryptedTrafficMirrorModel",    "DecryptedTrafficMirrorInterface",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-06T20:14:35.654933Z
# ============================================================================