"""
Pydantic Models for CMDB - monitoring/npu_hpe

Runtime validation models for monitoring/npu_hpe configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "NpuHpeModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.1
# Generated: 2026-01-18T15:06:46.702543Z
# ============================================================================