"""
Pydantic Models for MONITOR - router/bgp/neighbors

Runtime validation models for router/bgp/neighbors configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "NeighborsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-21T16:05:14.086102Z
# ============================================================================