from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_CONNECT_PROTOCOL: Literal["rpc-over-tcp", "rpc-over-http", "rpc-over-https"]
VALID_BODY_VALIDATE_SERVER_CERTIFICATE: Literal["disable", "enable"]
VALID_BODY_AUTH_TYPE: Literal["spnego", "ntlm", "kerberos"]
VALID_BODY_AUTH_LEVEL: Literal["connect", "call", "packet", "integrity", "privacy"]
VALID_BODY_HTTP_AUTH_TYPE: Literal["basic", "ntlm"]
VALID_BODY_SSL_MIN_PROTO_VERSION: Literal["default", "SSLv3", "TLSv1", "TLSv1-1", "TLSv1-2", "TLSv1-3"]
VALID_BODY_AUTO_DISCOVER_KDC: Literal["enable", "disable"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...