from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_STATUS: Literal["enable", "disable"]
VALID_BODY_TYPE: Literal["password", "radius", "tacacs+", "ldap", "saml"]
VALID_BODY_TWO_FACTOR: Literal["disable", "fortitoken", "fortitoken-cloud", "email", "sms"]
VALID_BODY_TWO_FACTOR_AUTHENTICATION: Literal["fortitoken", "email", "sms"]
VALID_BODY_TWO_FACTOR_NOTIFICATION: Literal["email", "sms"]
VALID_BODY_SMS_SERVER: Literal["fortiguard", "custom"]
VALID_BODY_AUTH_CONCURRENT_OVERRIDE: Literal["enable", "disable"]
VALID_BODY_USERNAME_SENSITIVITY: Literal["disable", "enable"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...