"""
Pydantic Models for CMDB - system/affinity_packet_redistribution

Runtime validation models for system/affinity_packet_redistribution configuration.
Generated from FortiOS schema version unknown.

Example Usage:
    >>> from hfortix_fortios.models.cmdb.system.affinity_packet_redistribution import 
    >>>
    >>> # Create with validation
    >>> obj = (
    ...     id=1,
    ...     name="example",
    ... )
    >>>
    >>> # Validation happens automatically
    >>> # ValidationError raised if constraints violated
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator
from typing import Any, Literal, Optional

# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================


# ============================================================================
# Main Model
# ============================================================================

class AffinityPacketRedistributionModel(BaseModel):
    """
    Pydantic model for system/affinity_packet_redistribution configuration.
    
    Configure packet redistribution.
    
    Validation Rules:        - id: min=0 max=4294967295 pattern=        - interface: max_length=15 pattern=        - rxqid: min=0 max=255 pattern=        - round_robin: pattern=        - affinity_cpumask: max_length=127 pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    id: int = Field(ge=0, le=4294967295, default=0, description="ID of the packet redistribution setting.")    
    interface: str = Field(max_length=15, default="", description="Physical interface name on which to perform packet redistribution.")  # datasource: ['system.interface.name']    
    rxqid: int = Field(ge=0, le=255, default=255, description="ID of the receive queue (when the interface has multiple queues) on which to perform packet redistribution (255 = all queues).")    
    round_robin: Literal["enable", "disable"] = Field(default="enable", description="Enable/disable round-robin redistribution to multiple CPUs.")    
    affinity_cpumask: str | None = Field(max_length=127, default="", description="Hexadecimal cpumask, empty value means all CPUs.")    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    @field_validator('interface')
    @classmethod
    def validate_interface(cls, v: Any) -> Any:
        """
        Validate interface field.
        
        Datasource: ['system.interface.name']
        
        Note:
            This validator only checks basic constraints.
            To validate that referenced object exists, query the API.
        """
        # Basic validation passed via Field() constraints
        # Additional datasource validation could be added here
        return v    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)


# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "AffinityPacketRedistributionModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-06T20:14:33.027783Z
# ============================================================================