"""
Pydantic Models for CMDB - system/dedicated_mgmt

Runtime validation models for system/dedicated_mgmt configuration.
Generated from FortiOS schema version unknown.

Example Usage:
    >>> from hfortix_fortios.models.cmdb.system.dedicated_mgmt import 
    >>>
    >>> # Create with validation
    >>> obj = (
    ...     name="example",
    ... )
    >>>
    >>> # Validation happens automatically
    >>> # ValidationError raised if constraints violated
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator
from typing import Any, Literal, Optional

# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================


# ============================================================================
# Main Model
# ============================================================================

class DedicatedMgmtModel(BaseModel):
    """
    Pydantic model for system/dedicated_mgmt configuration.
    
    Configure dedicated management.
    
    Validation Rules:        - status: pattern=        - interface: max_length=15 pattern=        - default_gateway: pattern=        - dhcp_server: pattern=        - dhcp_netmask: pattern=        - dhcp_start_ip: pattern=        - dhcp_end_ip: pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    status: Literal["enable", "disable"] | None = Field(default="disable", description="Enable/disable dedicated management.")    
    interface: str | None = Field(max_length=15, default="", description="Dedicated management interface.")  # datasource: ['system.interface.name']    
    default_gateway: str | None = Field(default="0.0.0.0", description="Default gateway for dedicated management interface.")    
    dhcp_server: Literal["enable", "disable"] | None = Field(default="disable", description="Enable/disable DHCP server on management interface.")    
    dhcp_netmask: str | None = Field(default="0.0.0.0", description="DHCP netmask.")    
    dhcp_start_ip: str | None = Field(default="0.0.0.0", description="DHCP start IP for dedicated management.")    
    dhcp_end_ip: str | None = Field(default="0.0.0.0", description="DHCP end IP for dedicated management.")    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    @field_validator('interface')
    @classmethod
    def validate_interface(cls, v: Any) -> Any:
        """
        Validate interface field.
        
        Datasource: ['system.interface.name']
        
        Note:
            This validator only checks basic constraints.
            To validate that referenced object exists, query the API.
        """
        # Basic validation passed via Field() constraints
        # Additional datasource validation could be added here
        return v    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)


# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DedicatedMgmtModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-06T20:14:32.986725Z
# ============================================================================