"""
Pydantic Models for CMDB - system/ipsec_aggregate

Runtime validation models for system/ipsec_aggregate configuration.
Generated from FortiOS schema version unknown.

Example Usage:
    >>> from hfortix_fortios.models.cmdb.system.ipsec_aggregate import 
    >>>
    >>> # Create with validation
    >>> obj = (
    ...     name=1,
    ...     name="example",
    ... )
    >>>
    >>> # Validation happens automatically
    >>> # ValidationError raised if constraints violated
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any, Optional
from enum import Enum

# ============================================================================
# Child Table Models
# ============================================================================

class IpsecAggregateMember(BaseModel):
    """
    Child table model for member.
    
    Member tunnels of the aggregate.
    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
    
    tunnel_name: str = Field(max_length=79, default="", description="Tunnel name.")  # datasource: ['vpn.ipsec.phase1-interface.name']
# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================

class IpsecAggregateAlgorithmEnum(str, Enum):
    """Allowed values for algorithm field."""
    L3 = "L3"    L4 = "L4"    ROUND_ROBIN = "round-robin"    REDUNDANT = "redundant"    WEIGHTED_ROUND_ROBIN = "weighted-round-robin"

# ============================================================================
# Main Model
# ============================================================================

class IpsecAggregateModel(BaseModel):
    """
    Pydantic model for system/ipsec_aggregate configuration.
    
    Configure an aggregate of IPsec tunnels.
    
    Validation Rules:        - name: max_length=15 pattern=        - member: pattern=        - algorithm: pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    name: str | None = Field(max_length=15, default="", description="IPsec aggregate name.")    
    member: list[Member] = Field(description="Member tunnels of the aggregate.")    
    algorithm: AlgorithmEnum | None = Field(default="round-robin", description="Frame distribution algorithm.")    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)


# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "IpsecAggregateModel",    "IpsecAggregateMember",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-06T20:14:33.292127Z
# ============================================================================