"""
Pydantic Models for CMDB - system/np6xlite

Runtime validation models for system/np6xlite configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "Np6xliteModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.2
# Generated: 2026-01-19T17:09:58.988954Z
# ============================================================================