"""
Pydantic Models for MONITOR - sdwan/link_monitor_metrics/report

Runtime validation models for sdwan/link_monitor_metrics/report configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "ReportModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T21:00:59.596262Z
# ============================================================================