from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_FORTILINK: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_SOURCE_IP: Literal["outbound", "fixed"]
VALID_BODY_MODE: Literal["static", "dhcp", "pppoe"]
VALID_BODY_DHCP_RELAY_INTERFACE_SELECT_METHOD: Literal["auto", "sdwan", "specify"]
VALID_BODY_DHCP_BROADCAST_FLAG: Literal["disable", "enable"]
VALID_BODY_DHCP_RELAY_SERVICE: Literal["disable", "enable"]
VALID_BODY_DHCP_RELAY_REQUEST_ALL_SERVER: Literal["disable", "enable"]
VALID_BODY_DHCP_RELAY_ALLOW_NO_END_OPTION: Literal["disable", "enable"]
VALID_BODY_DHCP_RELAY_TYPE: Literal["regular", "ipsec"]
VALID_BODY_DHCP_SMART_RELAY: Literal["disable", "enable"]
VALID_BODY_DHCP_RELAY_AGENT_OPTION: Literal["enable", "disable"]
VALID_BODY_DHCP_CLASSLESS_ROUTE_ADDITION: Literal["enable", "disable"]
VALID_BODY_ALLOWACCESS: Literal["ping", "https", "ssh", "snmp", "http", "telnet", "fgfm", "radius-acct", "probe-response", "fabric", "ftm", "speed-test", "scim"]
VALID_BODY_GWDETECT: Literal["enable", "disable"]
VALID_BODY_DETECTPROTOCOL: Literal["ping", "tcp-echo", "udp-echo"]
VALID_BODY_FAIL_DETECT: Literal["enable", "disable"]
VALID_BODY_FAIL_DETECT_OPTION: Literal["detectserver", "link-down"]
VALID_BODY_FAIL_ALERT_METHOD: Literal["link-failed-signal", "link-down"]
VALID_BODY_FAIL_ACTION_ON_EXTENDER: Literal["soft-restart", "hard-restart", "reboot"]
VALID_BODY_PPPOE_EGRESS_COS: Literal["cos0", "cos1", "cos2", "cos3", "cos4", "cos5", "cos6", "cos7"]
VALID_BODY_PPPOE_UNNUMBERED_NEGOTIATE: Literal["enable", "disable"]
VALID_BODY_DEFAULTGW: Literal["enable", "disable"]
VALID_BODY_DNS_SERVER_OVERRIDE: Literal["enable", "disable"]
VALID_BODY_DNS_SERVER_PROTOCOL: Literal["cleartext", "dot", "doh"]
VALID_BODY_AUTH_TYPE: Literal["auto", "pap", "chap", "mschapv1", "mschapv2"]
VALID_BODY_PPTP_CLIENT: Literal["enable", "disable"]
VALID_BODY_PPTP_AUTH_TYPE: Literal["auto", "pap", "chap", "mschapv1", "mschapv2"]
VALID_BODY_ARPFORWARD: Literal["enable", "disable"]
VALID_BODY_NDISCFORWARD: Literal["enable", "disable"]
VALID_BODY_BROADCAST_FORWARD: Literal["enable", "disable"]
VALID_BODY_BFD: Literal["global", "enable", "disable"]
VALID_BODY_L2FORWARD: Literal["enable", "disable"]
VALID_BODY_ICMP_SEND_REDIRECT: Literal["enable", "disable"]
VALID_BODY_ICMP_ACCEPT_REDIRECT: Literal["enable", "disable"]
VALID_BODY_VLANFORWARD: Literal["enable", "disable"]
VALID_BODY_STPFORWARD: Literal["enable", "disable"]
VALID_BODY_STPFORWARD_MODE: Literal["rpl-all-ext-id", "rpl-bridge-ext-id", "rpl-nothing"]
VALID_BODY_IPS_SNIFFER_MODE: Literal["enable", "disable"]
VALID_BODY_IDENT_ACCEPT: Literal["enable", "disable"]
VALID_BODY_IPMAC: Literal["enable", "disable"]
VALID_BODY_SUBST: Literal["enable", "disable"]
VALID_BODY_SPEED: Literal["auto", "10full", "10half", "100full", "100half", "100auto", "1000full", "1000auto"]
VALID_BODY_STATUS: Literal["up", "down"]
VALID_BODY_NETBIOS_FORWARD: Literal["disable", "enable"]
VALID_BODY_TYPE: Literal["physical", "vlan", "aggregate", "redundant", "tunnel", "vdom-link", "loopback", "switch", "vap-switch", "wl-mesh", "fext-wan", "vxlan", "geneve", "switch-vlan", "emac-vlan", "lan-extension"]
VALID_BODY_DEDICATED_TO: Literal["none", "management"]
VALID_BODY_WCCP: Literal["enable", "disable"]
VALID_BODY_NETFLOW_SAMPLER: Literal["disable", "tx", "rx", "both"]
VALID_BODY_SFLOW_SAMPLER: Literal["enable", "disable"]
VALID_BODY_DROP_FRAGMENT: Literal["enable", "disable"]
VALID_BODY_SRC_CHECK: Literal["enable", "disable"]
VALID_BODY_SAMPLE_DIRECTION: Literal["tx", "rx", "both"]
VALID_BODY_EXPLICIT_WEB_PROXY: Literal["enable", "disable"]
VALID_BODY_EXPLICIT_FTP_PROXY: Literal["enable", "disable"]
VALID_BODY_PROXY_CAPTIVE_PORTAL: Literal["enable", "disable"]
VALID_BODY_EXTERNAL: Literal["enable", "disable"]
VALID_BODY_MTU_OVERRIDE: Literal["enable", "disable"]
VALID_BODY_VLAN_PROTOCOL: Literal["8021q", "8021ad"]
VALID_BODY_LACP_MODE: Literal["static", "passive", "active"]
VALID_BODY_LACP_HA_SECONDARY: Literal["enable", "disable"]
VALID_BODY_SYSTEM_ID_TYPE: Literal["auto", "user"]
VALID_BODY_LACP_SPEED: Literal["slow", "fast"]
VALID_BODY_MIN_LINKS_DOWN: Literal["operational", "administrative"]
VALID_BODY_ALGORITHM: Literal["L2", "L3", "L4", "NPU-GRE", "Source-MAC"]
VALID_BODY_AGGREGATE_TYPE: Literal["physical", "vxlan"]
VALID_BODY_PRIORITY_OVERRIDE: Literal["enable", "disable"]
VALID_BODY_SECURITY_MODE: Literal["none", "captive-portal", "802.1X"]
VALID_BODY_SECURITY_MAC_AUTH_BYPASS: Literal["mac-auth-only", "enable", "disable"]
VALID_BODY_SECURITY_IP_AUTH_BYPASS: Literal["enable", "disable"]
VALID_BODY_DEVICE_IDENTIFICATION: Literal["enable", "disable"]
VALID_BODY_EXCLUDE_SIGNATURES: Literal["iot", "ot"]
VALID_BODY_DEVICE_USER_IDENTIFICATION: Literal["enable", "disable"]
VALID_BODY_LLDP_RECEPTION: Literal["enable", "disable", "vdom"]
VALID_BODY_LLDP_TRANSMISSION: Literal["enable", "disable", "vdom"]
VALID_BODY_MONITOR_BANDWIDTH: Literal["enable", "disable"]
VALID_BODY_VRRP_VIRTUAL_MAC: Literal["enable", "disable"]
VALID_BODY_ROLE: Literal["lan", "wan", "dmz", "undefined"]
VALID_BODY_SECONDARY_IP: Literal["enable", "disable"]
VALID_BODY_PRESERVE_SESSION_ROUTE: Literal["enable", "disable"]
VALID_BODY_AUTO_AUTH_EXTENSION_DEVICE: Literal["enable", "disable"]
VALID_BODY_AP_DISCOVER: Literal["enable", "disable"]
VALID_BODY_FORTILINK_NEIGHBOR_DETECT: Literal["lldp", "fortilink"]
VALID_BODY_IP_MANAGED_BY_FORTIIPAM: Literal["inherit-global", "enable", "disable"]
VALID_BODY_MANAGED_SUBNETWORK_SIZE: Literal["4", "8", "16", "32", "64", "128", "256", "512", "1024", "2048", "4096", "8192", "16384", "32768", "65536", "131072", "262144", "524288", "1048576", "2097152", "4194304", "8388608", "16777216"]
VALID_BODY_FORTILINK_SPLIT_INTERFACE: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_ACCESS_VLAN: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_RSPAN_MODE: Literal["disable", "enable"]
VALID_BODY_SWITCH_CONTROLLER_NETFLOW_COLLECT: Literal["disable", "enable"]
VALID_BODY_SWITCH_CONTROLLER_IGMP_SNOOPING: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_IGMP_SNOOPING_PROXY: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_IGMP_SNOOPING_FAST_LEAVE: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_DHCP_SNOOPING: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_DHCP_SNOOPING_VERIFY_MAC: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_DHCP_SNOOPING_OPTION82: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_ARP_INSPECTION: Literal["enable", "disable", "monitor"]
VALID_BODY_SWITCH_CONTROLLER_FEATURE: Literal["none", "default-vlan", "quarantine", "rspan", "voice", "video", "nac", "nac-segment"]
VALID_BODY_SWITCH_CONTROLLER_IOT_SCANNING: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_OFFLOAD: Literal["enable", "disable"]
VALID_BODY_SWITCH_CONTROLLER_OFFLOAD_GW: Literal["enable", "disable"]
VALID_BODY_EAP_SUPPLICANT: Literal["enable", "disable"]
VALID_BODY_EAP_METHOD: Literal["tls", "peap"]
VALID_BODY_DEFAULT_PURDUE_LEVEL: Literal["1", "1.5", "2", "2.5", "3", "3.5", "4", "5", "5.5"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...