from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_PORTS_DEFINED: Literal["source", "destination"]
VALID_BODY_SERVER_TYPE: Literal["forward", "proxy"]
VALID_BODY_AUTHENTICATION: Literal["enable", "disable"]
VALID_BODY_FORWARD_METHOD: Literal["GRE", "L2", "any"]
VALID_BODY_CACHE_ENGINE_METHOD: Literal["GRE", "L2"]
VALID_BODY_SERVICE_TYPE: Literal["auto", "standard", "dynamic"]
VALID_BODY_PRIMARY_HASH: Literal["src-ip", "dst-ip", "src-port", "dst-port"]
VALID_BODY_ASSIGNMENT_BUCKET_FORMAT: Literal["wccp-v2", "cisco-implementation"]
VALID_BODY_RETURN_METHOD: Literal["GRE", "L2", "any"]
VALID_BODY_ASSIGNMENT_METHOD: Literal["HASH", "MASK", "any"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...