"""
Pydantic Models for MONITOR - endpoint_control/summary

Runtime validation models for endpoint_control/summary configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "SummaryModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-21T16:05:14.471373Z
# ============================================================================