"""
Pydantic Models for MONITOR - system/config_revision/update_comments

Runtime validation models for system/config_revision/update_comments configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "UpdateCommentsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-09T11:38:31.193656Z
# ============================================================================