"""
Pydantic Models for MONITOR - user/fsso/refresh_server

Runtime validation models for user/fsso/refresh_server configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "RefreshServerModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-03T21:12:46.962065Z
# ============================================================================