"""
Pydantic Models for MONITOR - ips/hold_signatures

Runtime validation models for ips/hold_signatures configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "HoldSignaturesModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-16T10:37:40.180995Z
# ============================================================================