from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_MED_TLVS: Literal["inventory-management", "network-policy", "power-management", "location-identification"]
VALID_BODY_802_1_TLVS: Literal["port-vlan-id"]
VALID_BODY_802_3_TLVS: Literal["max-frame-size", "power-negotiation"]
VALID_BODY_AUTO_ISL: Literal["disable", "enable"]
VALID_BODY_AUTO_MCLAG_ICL: Literal["disable", "enable"]
VALID_BODY_AUTO_ISL_AUTH: Literal["legacy", "strict", "relax"]
VALID_BODY_AUTO_ISL_AUTH_ENCRYPT: Literal["none", "mixed", "must"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...