from typing import Any, Literal

# Enum type aliases for validation
VALID_BODY_QUERIES: Literal["disable", "enable"]
VALID_BODY_SECURITY_LEVEL: Literal["no-auth-no-priv", "auth-no-priv", "auth-priv"]
VALID_BODY_AUTH_PROTO: Literal["md5", "sha1", "sha224", "sha256", "sha384", "sha512"]
VALID_BODY_PRIV_PROTO: Literal["aes128", "aes192", "aes192c", "aes256", "aes256c", "des"]

# Metadata dictionaries
FIELD_TYPES: dict[str, str]
FIELD_DESCRIPTIONS: dict[str, str]
FIELD_CONSTRAINTS: dict[str, dict[str, Any]]
NESTED_SCHEMAS: dict[str, dict[str, Any]]
FIELDS_WITH_DEFAULTS: dict[str, Any]

# Helper functions
def get_field_type(field_name: str) -> str | None: ...
def get_field_description(field_name: str) -> str | None: ...
def get_field_default(field_name: str) -> Any: ...
def get_field_constraints(field_name: str) -> dict[str, Any]: ...
def get_nested_schema(field_name: str) -> dict[str, Any] | None: ...
def get_field_metadata(field_name: str) -> dict[str, Any]: ...
def validate_field_value(field_name: str, value: Any) -> bool: ...
def get_all_fields() -> list[str]: ...
def get_required_fields() -> list[str]: ...
def get_schema_info() -> dict[str, Any]: ...