"""
Pydantic Models for MONITOR - switch_controller/mclag_icl/tier_plus_candidates

Runtime validation models for switch_controller/mclag_icl/tier_plus_candidates configuration.
Generated from FortiOS schema version unknown.

Example Usage:
    >>> from hfortix_fortios.models.monitor.switch_controller.mclag_icl.tier_plus_candidates import 
    >>>
    >>> # Create with validation
    >>> obj = (
    ...     name="example",
    ... )
    >>>
    >>> # Validation happens automatically
    >>> # ValidationError raised if constraints violated
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "TierPlusCandidatesModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-09T10:28:33.136027Z
# ============================================================================