"""
Pydantic Models for MONITOR - router/ospf/neighbors

Runtime validation models for router/ospf/neighbors configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "NeighborsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-01T23:53:05.482182Z
# ============================================================================