"""
Pydantic Models for MONITOR - webfilter/malicious_urls/stat

Runtime validation models for webfilter/malicious_urls/stat configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "StatModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-05T01:53:54.283901Z
# ============================================================================