"""
Pydantic Models for MONITOR - firewall/address_dynamic

Runtime validation models for firewall/address_dynamic configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "AddressDynamicModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T22:00:18.979737Z
# ============================================================================