"""
Pydantic Models for MONITOR - firewall/address6_dynamic

Runtime validation models for firewall/address6_dynamic configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "Address6DynamicModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-16T10:37:39.603705Z
# ============================================================================