"""
Pydantic Models for MONITOR - firewall/internet_service_details

Runtime validation models for firewall/internet_service_details configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "InternetServiceDetailsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T21:00:59.350215Z
# ============================================================================