"""
Pydantic Models for MONITOR - firewall/internet_service_reputation

Runtime validation models for firewall/internet_service_reputation configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "InternetServiceReputationModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T22:00:19.418173Z
# ============================================================================