"""
Pydantic Models for MONITOR - firewall/local_in

Runtime validation models for firewall/local_in configuration.
Generated from FortiOS schema version unknown.

Example Usage:
    >>> from hfortix_fortios.models.monitor.firewall.local_in import 
    >>>
    >>> # Create with validation
    >>> obj = (
    ...     name="example",
    ... )
    >>>
    >>> # Validation happens automatically
    >>> # ValidationError raised if constraints violated
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "LocalInModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-09T10:28:33.169621Z
# ============================================================================