"""
Pydantic Models for MONITOR - firewall/vip_overlap

Runtime validation models for firewall/vip_overlap configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "VipOverlapModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-01T23:53:05.126735Z
# ============================================================================