"""
Pydantic Models for MONITOR - system/firmware

Runtime validation models for system/firmware configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "FirmwareModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-05T01:53:53.573592Z
# ============================================================================