"""
Pydantic Models for MONITOR - system/running_processes

Runtime validation models for system/running_processes configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "RunningProcessesModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-05T01:53:53.148743Z
# ============================================================================