"""
Pydantic Models for CMDB - ips/sensor

Runtime validation models for ips/sensor configuration.
Generated from FortiOS schema version unknown.

Example Usage:
    >>> from hfortix_fortios.models.cmdb.ips.sensor import 
    >>>
    >>> # Create with validation
    >>> obj = (
    ...     name=1,
    ...     name="example",
    ... )
    >>>
    >>> # Validation happens automatically
    >>> # ValidationError raised if constraints violated
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator
from typing import Any, Literal, Optional

# ============================================================================
# Child Table Models
# ============================================================================

class SensorEntries(BaseModel):
    """
    Child table model for entries.
    
    IPS sensor filter.
    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
    
    id: int | None = Field(ge=0, le=4294967295, default=0, description="Rule ID in IPS database (0 - 4294967295).")    
    rule: list[Rule] = Field(default=None, description="Identifies the predefined or custom IPS signatures to add to the sensor.")    
    location: list[Location] = Field(default="all", description="Protect client or server traffic.")    
    severity: list[Severity] = Field(default="all", description="Relative severity of the signature, from info to critical. Log messages generated by the signature include the severity.")    
    protocol: list[Protocol] = Field(default="all", description="Protocols to be examined. Use all for every protocol and other for unlisted protocols.")    
    os: list[Os] = Field(default="all", description="Operating systems to be protected. Use all for every operating system and other for unlisted operating systems.")    
    application: list[Application] = Field(default="all", description="Operating systems to be protected. Use all for every application and other for unlisted application.")    
    default_action: Literal["all", "pass", "block"] | None = Field(default="all", description="Signature default action filter.")    
    default_status: Literal["all", "enable", "disable"] | None = Field(default="all", description="Signature default status filter.")    
    cve: list[Cve] = Field(default=None, description="List of CVE IDs of the signatures to add to the sensor.")    
    vuln_type: list[VulnType] = Field(default=None, description="List of signature vulnerability types to filter by.")    
    last_modified: str | None = Field(default="", description="Filter by signature last modified date. Formats: before <date>, after <date>, between <start-date> <end-date>.")    
    status: Literal["disable", "enable", "default"] | None = Field(default="default", description="Status of the signatures included in filter. Only those filters with a status to enable are used.")    
    log: Literal["disable", "enable"] | None = Field(default="enable", description="Enable/disable logging of signatures included in filter.")    
    log_packet: Literal["disable", "enable"] | None = Field(default="disable", description="Enable/disable packet logging. Enable to save the packet that triggers the filter. You can download the packets in pcap format for diagnostic use.")    
    log_attack_context: Literal["disable", "enable"] | None = Field(default="disable", description="Enable/disable logging of attack context: URL buffer, header buffer, body buffer, packet buffer.")    
    action: ActionEnum | None = Field(default="default", description="Action taken with traffic in which signatures are detected.")    
    rate_count: int | None = Field(ge=0, le=65535, default=0, description="Count of the rate.")    
    rate_duration: int | None = Field(ge=1, le=65535, default=60, description="Duration (sec) of the rate.")    
    rate_mode: Literal["periodical", "continuous"] | None = Field(default="continuous", description="Rate limit mode.")    
    rate_track: RateTrackEnum | None = Field(default="none", description="Track the packet protocol field.")    
    exempt_ip: list[ExemptIp] = Field(default=None, description="Traffic from selected source or destination IP addresses is exempt from this signature.")    
    quarantine: Literal["none", "attacker"] | None = Field(default="none", description="Quarantine method.")    
    quarantine_expiry: str | None = Field(default="5m", description="Duration of quarantine. (Format ###d##h##m, minimum 1m, maximum 364d23h59m, default = 5m). Requires quarantine set to attacker.")    
    quarantine_log: Literal["disable", "enable"] | None = Field(default="enable", description="Enable/disable quarantine logging.")
# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================


# ============================================================================
# Main Model
# ============================================================================

class SensorModel(BaseModel):
    """
    Pydantic model for ips/sensor configuration.
    
    Configure IPS sensor.
    
    Validation Rules:        - name: max_length=47 pattern=        - comment: max_length=255 pattern=        - replacemsg_group: max_length=35 pattern=        - block_malicious_url: pattern=        - scan_botnet_connections: pattern=        - extended_log: pattern=        - entries: pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    name: str = Field(max_length=47, default="", description="Sensor name.")    
    comment: str | None = Field(max_length=255, default=None, description="Comment.")    
    replacemsg_group: str | None = Field(max_length=35, default="", description="Replacement message group.")  # datasource: ['system.replacemsg-group.name']    
    block_malicious_url: Literal["disable", "enable"] | None = Field(default="disable", description="Enable/disable malicious URL blocking.")    
    scan_botnet_connections: Literal["disable", "block", "monitor"] | None = Field(default="disable", description="Block or monitor connections to Botnet servers, or disable Botnet scanning.")    
    extended_log: Literal["enable", "disable"] | None = Field(default="disable", description="Enable/disable extended logging.")    
    entries: list[Entries] = Field(default=None, description="IPS sensor filter.")    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    @field_validator('replacemsg_group')
    @classmethod
    def validate_replacemsg_group(cls, v: Any) -> Any:
        """
        Validate replacemsg_group field.
        
        Datasource: ['system.replacemsg-group.name']
        
        Note:
            This validator only checks basic constraints.
            To validate that referenced object exists, query the API.
        """
        # Basic validation passed via Field() constraints
        # Additional datasource validation could be added here
        return v    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)


# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "SensorModel",    "SensorEntries",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-06T20:14:33.498759Z
# ============================================================================