"""
Pydantic Models for SERVICE - system/fabric_time_in_sync

Runtime validation models for system/fabric_time_in_sync configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "FabricTimeInSyncModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-15T22:00:19.642779Z
# ============================================================================