"""
Pydantic Models for MONITOR - switch_controller/managed_switch/dhcp_snooping

Runtime validation models for switch_controller/managed_switch/dhcp_snooping configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DhcpSnoopingModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-03T21:12:47.154909Z
# ============================================================================