"""
Pydantic Models for MONITOR - log/hourly_disk_usage

Runtime validation models for log/hourly_disk_usage configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "HourlyDiskUsageModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-02-03T16:51:09.296411Z
# ============================================================================